In [1]:
import numpy as np

In [16]:
goal = 200
coins = [200, 100, 50, 20 , 10, 5, 2, 1][::-1]
totals = [0 for _ in range(goal+1)]
totals[0] = 1
for c in coins:
    for j in range(c, len(totals)):
        totals[j]+= totals[j - c]

In [17]:
totals

[1,
 1,
 2,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 11,
 12,
 15,
 16,
 19,
 22,
 25,
 28,
 31,
 34,
 41,
 44,
 51,
 54,
 61,
 68,
 75,
 82,
 89,
 96,
 109,
 116,
 129,
 136,
 149,
 162,
 175,
 188,
 201,
 214,
 236,
 249,
 271,
 284,
 306,
 328,
 350,
 372,
 394,
 416,
 451,
 473,
 508,
 530,
 565,
 600,
 635,
 670,
 705,
 740,
 793,
 828,
 881,
 916,
 969,
 1022,
 1075,
 1128,
 1181,
 1234,
 1311,
 1364,
 1441,
 1494,
 1571,
 1648,
 1725,
 1802,
 1879,
 1956,
 2064,
 2141,
 2249,
 2326,
 2434,
 2542,
 2650,
 2758,
 2866,
 2974,
 3121,
 3229,
 3376,
 3484,
 3631,
 3778,
 3925,
 4072,
 4219,
 4366,
 4563,
 4710,
 4907,
 5054,
 5251,
 5448,
 5645,
 5842,
 6039,
 6236,
 6495,
 6692,
 6951,
 7148,
 7407,
 7666,
 7925,
 8184,
 8443,
 8702,
 9038,
 9297,
 9633,
 9892,
 10228,
 10564,
 10900,
 11236,
 11572,
 11908,
 12337,
 12673,
 13102,
 13438,
 13867,
 14296,
 14725,
 15154,
 15583,
 16012,
 16553,
 16982,
 17523,
 17952,
 18493,
 19034,
 19575,
 20116,
 20657,
 21198,
 21873,
 22414,
 23089,
 23630,
 24305,
 24980,
 25655,
 26330,
 27005,
 27680,
 28514,
 29189,
 30023,
 30698,
 31532,
 32366,
 33200,
 34034,
 34868,
 35702,
 36723,
 37557,
 38578,
 39412,
 40433,
 41454,
 42475,
 43496,
 44517,
 45538,
 46777,
 47798,
 49037,
 50058,
 51297,
 52536,
 53775,
 55014,
 56253,
 57492,
 58983,
 60222,
 61713,
 62952,
 64443,
 65934,
 67425,
 68916,
 70407,
 71898,
 73682]